# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://flora.db.elephantsql.com/prqtlvtt
    username: prqtlvtt
    password: BEshDvfjStsYq1Hp67VrLCDr6BKprotu
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080
# Security configuration
security:
  user:
    name: user
password: user

